### ISSUE TITLE
Choop Model reorganisation

### ISSUE THREAD

**Issue by ed-cooper** [chooper100/Choop#7]
Files in the ChoopModel can be grouped to reduce the number of files per folder.

Option 1
====
- Statements
  - Iteration
    - ForLoop
    - ForeachLoop
    - ForeverLoop
    - RepeatLoop
    - WhileLoop
  - Selection
    - Condition
    - ConditionalBlock
    - SwitchStmt
    - IfStmt
  - Assignments
    - ArrayAssignStmt
    - ArrayReassignStmt
    - VarAssignStmt
    - AssignOperator
  - Misc
    - ReturnStmt
    - ScopedArrayDeclaration
    - ScopedVarDeclaration
    - ScopeDeclaration
- Expressions
  - ArrayLookupExpression
  - CompoundExpression
  - CompoundOperator
  - LookupExpression
  - TerminalExpression
  - TerminalType
  - UnaryExpression
  - UnaryOperator
- Declarations
  - ConstDeclaration
  - DataType
  - EventHandler
  - GlobalListDeclaration
  - GlobalVarDeclaration
  - MethodDeclaration
  - ModuleDeclaration
  - ParamDeclaration
  - SpriteDeclaration
  - UsingStmt
- Interfaces
  - ICompilable
  - IHasBody
  - IRule
  - IDeclaration
  - IMethod
  - IArrayDeclaration
  - ISpriteDeclaration
  - ITypedDeclaration
  - IVarDeclaration
  - IExpression
  - IAssignStmt
  - IStatement
  - IScopedDeclaration
- Misc
  - MethodCall
  - Project

Option 2
===
- Iteration
  - ForLoop
  - ForeachLoop
  - ForeverLoop
  - RepeatLoop
  - WhileLoop
- Selection
  - Condition
  - ConditionalBlock
  - SwitchStmt
  - IfStmt
- Assignments
  - ArrayAssignStmt
  - ArrayReassignStmt
  - AssignOperator
  - VarAssignStmt
- Expressions
  - ArrayLookupExpression
  - CompoundExpression
  - CompoundOperator
  - LookupExpression
  - TerminalExpression
  - TerminalType
  - UnaryExpression
  - UnaryOperator
- Methods
  - MethodDeclaration
  - ParamDeclaration
  - EventHandler
  - MethodCall
  - ReturnStmt
- Declarations
  - ConstDeclaration
  - GlobalListDeclaration
  - GlobalVarDeclaration
  - ScopedArrayDeclaration
  - ScopedVarDeclaration
  - ScopeDeclaration
- Sprites
  - SpriteDeclaration
  - ModuleDeclaration
  - UsingStmt
- Interfaces
  - ICompilable
  - IHasBody
  - IRule
  - IDeclaration
  - IMethod
  - IArrayDeclaration
  - ISpriteDeclaration
  - ITypedDeclaration
  - IVarDeclaration
  - IExpression
  - IAssignStmt
  - IStatement
  - IScopedDeclaration
- DataType
- Project

**Comment by ed-cooper** [comment]
# Option 2 Refined
- Iteration
  - ForLoop
  - ForeachLoop
  - ForeverLoop
  - RepeatLoop
  - WhileLoop
- Selection
  - Condition
  - ConditionalBlock
  - SwitchStmt
  - IfStmt
- Assignments
  - ArrayAssignStmt
  - ArrayReassignStmt
  - AssignOperator
  - VarAssignStmt
  - IAssignStmt
- Expressions
  - ArrayLookupExpression
  - CompoundExpression
  - CompoundOperator
  - LookupExpression
  - TerminalExpression
  - TerminalType
  - UnaryExpression
  - UnaryOperator
  - IExpression
- Methods
  - MethodDeclaration
  - ParamDeclaration
  - EventHandler
  - MethodCall
  - ReturnStmt
  - IMethod
- Declarations
  - ConstDeclaration
  - GlobalListDeclaration
  - GlobalVarDeclaration
  - ScopedArrayDeclaration
  - ScopedVarDeclaration
  - ScopeDeclaration
  - IArrayDeclaration
  - IVarDeclaration
  - IScopedDeclaration
- Sprites
  - SpriteDeclaration
  - ModuleDeclaration
  - UsingStmt
  - ISpriteDeclaration
- DataType
- Project
- ICompilable
- IHasBody
- IRule
- IDeclaration
- ITypedDeclaration
- IStatement

**Comment by ed-cooper** [comment]
Completed

**Comment by csnewman** [comment]
🎉
